---
# tasks file for docker-ce-ansible-role

- name: Remove previous docker installation
  apt:
    name: "{{ item.package }}"
    state: absent
  with_items: "{{ docker_cleanup_packages_Ubuntu }}"

- name: Install prerequisite packages
  apt:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ docker_prerequisite_packages_Ubuntu }}"

- name: Import Docker CE repository gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add Docker CE repository
  apt_repository:
#    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu zesty stable"
    state: present

- name: Install docker-ce and docker-compose
  apt:
    name: "{{ item }}"
    update_cache: yes
    install_recommends: yes
    state: present
  with_items:
  - docker-ce
  - docker-compose

- name: Enable Docker CE service on startup
  service:
    name: docker
    state: started
    enabled: yes
